In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-mpnet-base-v2")  # all-MiniLM-L6-v2 if you want faster but noisier results
model

/workspaces/applsoftcomp-sprint-m04/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 520.76it/s]

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'MPNetModel'})
  (1): Pooling({'embedding_dimension': 768, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)

In [2]:
import pandas as pd
uni_df = pd.read_csv("../data/universities.csv")

In [3]:
uni_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    156 non-null    str
 1   type    156 non-null    str
 2   region  156 non-null    str
dtypes: str(3)
memory usage: 3.8 KB

In [4]:

print(f"{len(uni_df)} unis across {uni_df['region'].nunique()} regions.")
uni_df.head()

156 unis across 4 regions.

                                          name type     region
0                             Brown University  Ivy  Northeast
1  Columbia University in the City of New York  Ivy  Northeast
2                           Cornell University  Ivy  Northeast
3                            Dartmouth College  Ivy  Northeast
4                           Harvard University  Ivy  Northeast

In [5]:

print(f"{len(uni_df)} unis across {uni_df['type'].nunique()} types.")
uni_df.head(50)

156 unis across 14 types.

,name,type,region
0,Brown University,Ivy,Northeast
1,Columbia University in the City of New York,Ivy,Northeast
2,Cornell University,Ivy,Northeast
3,Dartmouth College,Ivy,Northeast
4,Harvard University,Ivy,Northeast
5,Princeton University,Ivy,Northeast
6,University of Pennsylvania,Ivy,Northeast
7,Yale University,Ivy,Northeast
8,George Washington University,Elite Private,South
9,Johns Hopkins University,Elite Private,South
10,New York University,Elite Private,Northeast
11,Northeastern University,Elite Private,Northeast
12,Northwestern University,Elite Private,Midwest
13,Pacific Oaks College,Elite Private,West
14,Rice University,Elite Private,South
15,Stanford University,Elite Private,West
16,Tufts University,Elite Private,Northeast
17,University of Chicago,Elite Private,Midwest
18,University of Southern California,Elite Private,West
19,Vanderbilt University,Elite Private,South
20,Washington University in St Louis,Elite Private,Midwest
21,California Institute of Technology,Tech,West
22,California Polytechnic State University-San Lu...,Tech,West
23,Colorado School of Mines,Tech,West
24,Franklin W Olin College of Engineering,Tech,Northeast
25,Georgia Institute of Technology-Main Campus,Tech,South
26,Illinois Institute of Technology,Tech,Midwest
27,Massachusetts Institute of Technology,Tech,Northeast
28,Rose-Hulman Institute of Technology,Tech,Midwest
29,Webb Institute,Tech,Northeast
30,Worcester Polytechnic Institute,Tech,Northeast
31,Indiana University-Bloomington,Public Flagship,Midwest
32,Michigan State University,Public Flagship,Midwest
33,Ohio State University-Main Campus,Public Flagship,Midwest
34,Purdue University-Main Campus,Public Flagship,Midwest
35,Rutgers University-New Brunswick,Public Flagship,Northeast
36,The University of Texas at Austin,Public Flagship,South
37,University of Arizona,Public Flagship,West
38,University of California-Berkeley,Public Flagship,West
39,University of California-Irvine,Public Flagship,West
40,University of California-Los Angeles,Public Flagship,West
41,University of California-San Diego,Public Flagship,West
42,University of Colorado Boulder,Public Flagship,West
43,University of Florida,Public Flagship,South
44,University of Georgia,Public Flagship,South
45,University of Illinois Urbana-Champaign,Public Flagship,Midwest
46,University of Iowa,Public Flagship,Midwest
47,University of Maryland-College Park,Public Flagship,South
48,University of Michigan-Ann Arbor,Public Flagship,Midwest
49,University of Minnesota-Twin Cities,Public Flagship,Midwest

In [6]:
uni_df['type'].unique()

<StringArray>
[              'Ivy',     'Elite Private',              'Tech',
   'Public Flagship',   'Public Regional',      'Liberal Arts',
              'HBCU',         'Religious',            'Womens',
   'Service Academy',        'For-Profit', 'Community College',
            'Tribal',  'Specialized Arts']
Length: 14, dtype: str

In [7]:
import numpy as np

def make_axis(positive_words, negative_words, embedding_model):
    """Return a unit-length semantic axis from two word sets."""

    # get the embeddings for each pole
    pos_emb = embedding_model.encode(positive_words, normalize_embeddings=True)
    neg_emb = embedding_model.encode(negative_words, normalize_embeddings=True)

    # Compute the pole centroids
    # axis = 0 means "average across the rows, keep the columns (dims) intact"
    # since pos_emb is shape (num_pos_words, embedding_dim), the mean is shape (embedding_dim,)
    pole_pos = pos_emb.mean(axis=0)  # (embedding_dim,)
    pole_neg = neg_emb.mean(axis=0)  # (embedding_dim,)

    # The axis is the difference between the two centroids, normalized to unit length.
    v = pole_pos - pole_neg

    v = v / (np.linalg.norm(v) + 1e-10)  # add small epsilon to prevent division by zero

    return v / (np.linalg.norm(v) + 1e-10)

In [8]:
def score_words(words, axis, embedding_model):
    """Project each word onto the axis. Returns one score per word."""

    emb = embedding_model.encode(list(words), normalize_embeddings=True)

    # Projection to the axis is just a dot product (since the axis is unit-length).
    # @ is matrix multiplication in NumPy. Since `emb` is shape (num_words, embedding_dim) and `axis` is shape (embedding_dim,), the result is shape (num_words,), which is exactly what we want: one score per word.
    proj = emb @ axis

    return proj

In [9]:
# semantic axes
axis1_pos = [
    "elite",
    "selective",
    "prestigious",
]

axis1_neg = [
    "accessible",
    "open",
    "local",
]

In [10]:
axis_prestige = make_axis(axis1_pos, axis1_neg, model)

In [11]:
axis2_pos = [
    "urban",
    "big city",
    "downtown",
]
axis2_neg = [
    "small town",
    "suburban",
    "rural",
]

In [12]:
axis_setting = make_axis(axis2_pos, axis2_neg, model)

In [13]:
x = score_words(uni_df["name"].tolist(), axis_prestige, model)
y = score_words(uni_df["name"].tolist(), axis_setting, model)
df_scored = uni_df.assign(x=x, y=y)
df_scored.head()

,name,type,region,x,y
0,Brown University,Ivy,Northeast,0.101672,0.134888
1,Columbia University in the City of New York,Ivy,Northeast,0.092813,0.204181
2,Cornell University,Ivy,Northeast,0.044057,0.072553
3,Dartmouth College,Ivy,Northeast,0.054549,0.024374
4,Harvard University,Ivy,Northeast,0.135196,0.060730

In [14]:
pd.set_option('display.max_rows', None)
df_scored.head(100)

,name,type,region,x,y
0,Brown University,Ivy,Northeast,0.101672,0.134888
1,Columbia University in the City of New York,Ivy,Northeast,0.092813,0.204181
2,Cornell University,Ivy,Northeast,0.044057,0.072553
3,Dartmouth College,Ivy,Northeast,0.054549,0.024374
4,Harvard University,Ivy,Northeast,0.135196,0.060730
5,Princeton University,Ivy,Northeast,0.092167,0.022035
6,University of Pennsylvania,Ivy,Northeast,0.063431,0.085402
7,Yale University,Ivy,Northeast,0.154960,0.108798
8,George Washington University,Elite Private,South,0.051459,0.092588
9,Johns Hopkins University,Elite Private,South,0.100434,0.113219
10,New York University,Elite Private,Northeast,0.095341,0.197977
11,Northeastern University,Elite Private,Northeast,0.045510,0.065832
12,Northwestern University,Elite Private,Midwest,0.029488,0.118368
13,Pacific Oaks College,Elite Private,West,0.046533,0.067967
14,Rice University,Elite Private,South,0.061954,0.035366
15,Stanford University,Elite Private,West,0.130341,0.070777
16,Tufts University,Elite Private,Northeast,0.112898,0.076221
17,University of Chicago,Elite Private,Midwest,0.073098,0.147637
18,University of Southern California,Elite Private,West,0.063435,0.077513
19,Vanderbilt University,Elite Private,South,0.058861,-0.003290
20,Washington University in St Louis,Elite Private,Midwest,-0.011735,0.138440
21,California Institute of Technology,Tech,West,0.082718,0.045315
22,California Polytechnic State University-San Lu...,Tech,West,0.061154,0.072295
23,Colorado School of Mines,Tech,West,0.079747,-0.054469
24,Franklin W Olin College of Engineering,Tech,Northeast,0.002201,0.054997
25,Georgia Institute of Technology-Main Campus,Tech,South,0.002252,-0.025491
26,Illinois Institute of Technology,Tech,Midwest,0.086713,0.012248
27,Massachusetts Institute of Technology,Tech,Northeast,0.112828,0.042237
28,Rose-Hulman Institute of Technology,Tech,Midwest,0.027231,0.058528
29,Webb Institute,Tech,Northeast,0.050276,-0.014724
30,Worcester Polytechnic Institute,Tech,Northeast,0.071100,0.033673
31,Indiana University-Bloomington,Public Flagship,Midwest,0.064245,0.036997
32,Michigan State University,Public Flagship,Midwest,0.092943,0.053664
33,Ohio State University-Main Campus,Public Flagship,Midwest,-0.050889,0.118060
34,Purdue University-Main Campus,Public Flagship,Midwest,-0.037366,0.056267
35,Rutgers University-New Brunswick,Public Flagship,Northeast,0.044913,0.072381
36,The University of Texas at Austin,Public Flagship,South,0.115237,0.112572
37,University of Arizona,Public Flagship,West,0.088770,0.090790
38,University of California-Berkeley,Public Flagship,West,0.049926,0.131625
39,University of California-Irvine,Public Flagship,West,0.068037,0.122873
40,University of California-Los Angeles,Public Flagship,West,0.060327,0.167011
41,University of California-San Diego,Public Flagship,West,0.084215,0.130832
42,University of Colorado Boulder,Public Flagship,West,0.034876,0.076753
43,University of Florida,Public Flagship,South,0.099176,0.075794
44,University of Georgia,Public Flagship,South,0.087904,0.032560
45,University of Illinois Urbana-Champaign,Public Flagship,Midwest,0.004712,0.105435
46,University of Iowa,Public Flagship,Midwest,0.085258,0.030311
47,University of Maryland-College Park,Public Flagship,South,0.039049,0.088770
48,University of Michigan-Ann Arbor,Public Flagship,Midwest,0.073333,0.094999
49,University of Minnesota-Twin Cities,Public Flagship,Midwest,0.054678,0.100996
50,University of North Carolina at Chapel Hill,Public Flagship,South,0.077994,0.093768
51,University of Virginia-Main Campus,Public Flagship,South,-0.044486,0.009932
52,University of Washington-Seattle Campus,Public Flagship,West,-0.037378,0.129711
53,University of Wisconsin-Madison,Public Flagship,Midwest,0.078658,0.089845
54,Colorado State University-Fort Collins,Public Regional,West,0.056441,0.024217
55,Florida International University,Public Regional,South,0.096464,0.040150
56,Florida State University,Public Regional,South,0.106189,0.050143
57,Iowa State University,Public Regional,Midwest,0.084821,0.022634
58,Mississippi State University,Public Regional,South,0.074027,0.029573
59,San Diego State University,Public Regional,West,0.038407,0.086158
60,The University of Alabama,Public Regional,South,0.120820,0.078064
61,University of Alabama at Birmingham,Public Regional,South,0.092775,0.105391
62,University of Alabama in Huntsville,Public Regional,South,0.084453,0.087721
63,University of Alaska Anchorage,Public Regional,West,-0.002827,0.089878
64,University of Alaska Southeast,Public Regional,West,0.022894,0.012935
65,University of Central Florida,Public Regional,South,0.074885,0.063633
66,University of Hawaii at Hilo,Public Regional,West,0.061927,0.080030
67,University of Hawaii at Manoa,Public Regional,West,0.056259,0.061194
68,University of Houston,Public Regional,South,0.096629,0.099112
69,University of Houston-Clear Lake,Public Regional,South,0.080023,0.059916
70,University of Houston-Victoria,Public Regional,South,0.062577,0.032091
71,Amherst College,Liberal Arts,Northeast,0.021571,0.051323
72,Bowdoin College,Liberal Arts,Northeast,-0.013768,-0.002608
73,Carleton College,Liberal Arts,Midwest,0.035999,0.039043
74,Claremont McKenna College,Liberal Arts,West,0.042557,0.050618
75,Colby College,Liberal Arts,Northeast,0.058398,0.035228
76,Davidson College,Liberal Arts,South,0.010200,0.064181
77,Grinnell College,Liberal Arts,Midwest,0.037142,-0.013131
78,Haverford College,Liberal Arts,Northeast,0.007425,0.066813
79,Kenyon College,Liberal Arts,Midwest,0.023721,0.023900
80,Middlebury College,Liberal Arts,Northeast,0.060998,0.028108
81,Oberlin College,Liberal Arts,Midwest,0.077920,0.083274
82,Pomona College,Liberal Arts,West,0.060975,0.057477
83,Reed College,Liberal Arts,West,0.074334,0.020631
84,Swarthmore College,Liberal Arts,Northeast,0.047378,0.071193
85,Whitman College,Liberal Arts,West,0.018236,0.062468
86,Williams College,Liberal Arts,Northeast,0.049268,0.062108
87,Clark Atlanta University,HBCU,South,0.022428,0.052679
88,Dillard University,HBCU,South,0.052859,0.101673
89,Fisk University,HBCU,South,0.069563,0.030892
90,Florida Agricultural and Mechanical University,HBCU,South,0.059342,-0.072223
91,Grambling State University,HBCU,South,0.057593,0.001028
92,Hampton University,HBCU,South,0.090886,0.111131
93,Howard University,HBCU,South,0.083508,0.026312
94,Morehouse College,HBCU,South,0.044019,-0.034232
95,Morehouse School of Medicine,HBCU,South,0.042091,0.038125
96,Morgan State University,HBCU,South,0.054806,0.032928
97,Tuskegee University,HBCU,South,0.113684,0.031977
98,Xavier University of Louisiana,HBCU,South,0.107470,0.058815
99,Baylor University,Religious,South,0.085442,0.050709

In [15]:
import plotly.express as px

In [21]:
fig = px.scatter(
    df_scored,
    x="x", y="y",
    color="type",
    symbol="type",
    color_discrete_sequence=px.colors.qualitative.Safe,
    hover_name="name",
)
fig.show()